### ISSUE TITLE
Entities deleted prior to expiration not removed from index

### ISSUE THREAD

**Issue by chrisowhite** [graphaware/neo4j-expire#12]
If a node/relationship is deleted prior to expiration it is left in the manual index. Since Neo4j recycles IDs, when a node/relationship is assigned an ID that's still in the TTL index after a delete, the new entity is deleted even if the new entity was not assigned a TTL.

**Comment by jasperblues** [comment]
This has been fixed in a pending (as yet unmerged) update.
