### ISSUE TITLE
Wrong ms value on older article on expire plugin 

### ISSUE THREAD

**Issue by InverseFalcon** [graphaware/neo4j-expire#15]
Not directly related to code but an older article, not sure where to put this.

Looking at this article from 2016:
https://graphaware.com/neo4j/2016/03/15/expiring-data-in-neo4j.html

we see this:

```
MATCH (p:Person {name:'Michal'})
MATCH (o:Organisation {name:'ACM'})
MERGE (p)-[:MEMBER_OF {ttl:2592000}]->(o)
```

> will cause the relationship to vanish in exactly 30 days (2,592,000 ms).

The ms value here, `2,592,000`, looks to be the value in seconds (`30*24*60*60`), it should be multiplied by 1000 to provide the ms value of 2,592,000,000.

**Comment by bachmanm** [comment]
well spotted, thanks! Fixed.
