### ISSUE TITLE
Protected access

### ISSUE THREAD

**Issue by sako9** [graphaware/neo4j-expire#2]
Hi, I'm trying to use the neo4j-expire in embedded mode but the constructor for the ExpirationModule is protected instead of public.

**Comment by ikwattro** [comment]
The `ExpirationModule` extends the `BaseTxDrivenModule` from the framework, instantiation is like it is written in the docs, you can check how we do it in the test suite for example : 

https://github.com/graphaware/neo4j-expire/blob/master/src/test/java/com/graphaware/neo4j/expire/ProgrammaticIntegrationTest.java#L487

**Comment by sako9** [comment]
I did follow the example in the docs but I get the error 'ExpirationModule(String,GraphDatabaseService,ExpirationConfiguration) has protected access in ExpirationModule'

**Comment by bachmanm** [comment]
You're right, sorry about that. Give me a couple of minutes

**Comment by ikwattro** [comment]
I was wrong, sorry. New link for the plugin : 

New version released.

http://products.graphaware.com/download/expire/graphaware-expire-3.0.3.39.3.jar

**Comment by sako9** [comment]
Thanks for the update, any idea when the new jar will be available in the maven central repository?

**Comment by bachmanm** [comment]
it's there
