### ISSUE TITLE
google-analytics within Neo4j

### ISSUE THREAD

**Issue by rittinger** [graphaware/neo4j-expire#6]
We are seeing the following exception over and over in our Neo4j logs:
2017-02-20 13:34:57.564+0000 WARN  [c.g.c.p.GoogleAnalyticsStatsCollector] Unable to collect stats Connect to www.google-analytics.com:80 [www.google-analytics.co
m/4.59.40.103, www.google-analytics.com/4.59.40.89, www.google-analytics.com/4.59.40.114, www.google-analytics.com/4.59.40.123, www.google-analytics.com/4.59.40.1
18, www.google-analytics.com/4.59.40.94, www.google-analytics.com/4.59.40.98, www.google-analytics.com/4.59.40.93, www.google-analytics.com/4.59.40.88, www.google
-analytics.com/4.59.40.109, www.google-analytics.com/4.59.40.84, www.google-analytics.com/4.59.40.113, www.google-analytics.com/4.59.40.119, www.google-analytics.
com/4.59.40.104, www.google-analytics.com/4.59.40.99, www.google-analytics.com/4.59.40.108] failed: Connection timed out (Connection timed out)
org.apache.http.conn.HttpHostConnectException: Connect to www.google-analytics.com:80 [www.google-analytics.com/4.59.40.103, www.google-analytics.com/4.59.40.89, 
www.google-analytics.com/4.59.40.114, www.google-analytics.com/4.59.40.123, www.google-analytics.com/4.59.40.118, www.google-analytics.com/4.59.40.94, www.google-
analytics.com/4.59.40.98, www.google-analytics.com/4.59.40.93, www.google-analytics.com/4.59.40.88, www.google-analytics.com/4.59.40.109, www.google-analytics.com
/4.59.40.84, www.google-analytics.com/4.59.40.113, www.google-analytics.com/4.59.40.119, www.google-analytics.com/4.59.40.104, www.google-analytics.com/4.59.40.99
, www.google-analytics.com/4.59.40.108] failed: Connection timed out (Connection timed out)

Our network security team will never allow this information to flow through our firewalls.  We thought we configured the Graphware Expire module correctly to turn off this logging but apparently not:
Within the neo4j.conf file:
com.graphaware.runtime.stats.disabled=true
com.graphaware.server.stats.disabled=true

Can you tell us how to turn off google analytics?

**Comment by bachmanm** [comment]
Could you try

com.graphaware.runtime.stats.disable=true
com.graphaware.server.stats.disable=true

**Comment by espiegelberg** [comment]
Please see https://github.com/graphaware/neo4j-framework/issues/59. Does this help?

**Comment by rittinger** [comment]
I didn't even notice the typo?!?!?  Trying now.

**Comment by rittinger** [comment]
Oh wait, we already have those (and they are correct I think):
com.graphaware.runtime.stats.disabled=true
com.graphaware.server.stats.disabled=true

**Comment by espiegelberg** [comment]
Which versions of the module and framework are you using? 

It's possible you have versions that predate the fix for this issue; you may want to try including both variants of the configuration (ie: com.graphaware.runtime.stats.disable and com.graphaware.runtime.stats.disabled, etc) to see if one or the other works.

**Comment by rittinger** [comment]
We're running neo4j 3.0.8 and graphaware expire module 3.0.7.44.4 (we didn't see a 3.0.8 version at the time we upgraded).

**Comment by espiegelberg** [comment]
Were you able to test using both variations of the configuration? For example:

```
com.graphaware.runtime.stats.disable=true
com.graphaware.runtime.stats.disabled=true

com.graphaware.server.stats.disable=true
com.graphaware.server.stats.disabled=true
```

**Comment by rittinger** [comment]
We tried both variations:
com.graphaware.runtime.stats.disable=true
com.graphaware.runtime.stats.disabled=true
com.graphaware.server.stats.disable=true
com.graphaware.server.stats.disabled=true
and neither worked.

**Comment by espiegelberg** [comment]
Could you please enter into your project, perform a "mvn clean dependency:tree > tree.txt", and provide the output of tree.txt here? That will provide the exact version numbers you are using and help us debug.

**Comment by rittinger** [comment]
This is a neo4j/graphaware issue.  Nothing to do with any project code we're deploying as we can start the graph without anything connecting to it and 30-35 minutes later, we'll lsee the first error in the neo4j/debug.log file. We're using neo4j 3.0.8 and graphaware expire modle 3.0.7.44.  The graphaware expire module itself is working, as we're assigning ttl attributes to nodes/relationships and they are being deleted as expected.  Our only issue is the google-analytics which we can't seem to turn off.

**Comment by espiegelberg** [comment]
I've spent some time investigating and have been so far unable to reproduce the issue.

I'm testing using a fresh Neo4j 3.0.8 install, deploying the GraphAware Expire module (version 3.0.7.44), deploying the graphaware-server library (version 3.0.7.44) to $neo4j_home/plugins/, and the stats collection is correctly disabled when using the following additions to ${neo4j_home}/conf/neo4j.properties:

com.graphaware.runtime.stats.disable=true
com.graphaware.runtime.stats.disabled=true

com.graphaware.server.stats.disable=true
com.graphaware.server.stats.disabled=true

My suggestion is to verify the version of the graphaware-server library you are making use of in your $neo4j_home/plugins.

At this point, unless you can provide more information to help reproduce the issue we will have to consider this issue closed.

**Comment by rremigius** [comment]
I'm experiencing the same issue. I'm on a network that cannot access Google Analytics, so every 5 minutes, an UnknownHostException appears in the neo4j log, with a stack trace from GraphAware. I've tried both versions of the configuration spelling as well.

I'm running Neo4j Community 3.1.1 and in my plugins directory I have the following GraphAware plugins:
graphaware-server-community-all-3.1.0.44.jar
graphaware-timetree-3.1.0.44.26.jar
graphaware-uuid-3.1.0.44.13.jar

**Comment by bachmanm** [comment]
replaced with https://github.com/graphaware/neo4j-framework/issues/66
